name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ulsmith/rpi-raspbian-apache-php

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        git pull --recurse-submodules
        git submodule update --remote --recursive
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
